language: python
python:
  - "3.8"
services:
  - docker
install:
  - pip install -r requirements.txt
  - docker pull thomasweise/docker-texlive-full
script:
  - doge render_pdf --profiles pdf
  - doge render_md --langs en --profiles md_for_github
deploy:
  provider: script
  script: doge commit_md_to_github --langs en --profiles md_for_github && doge release_pdf --profiles pdf
  on:
    branch: master
branches:
  only:
  - master
