name: Build and release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Install python requirements
        run: pip3 install -r requirements.txt
      - name: Pull docker container
        run: docker pull thomasweise/docker-texlive-full
      - name: Release .pdf
        env:
          GITHUB_TOKEN: ${{ secrets.KSBENDERBOT_GITHUB_TOKEN }}
        run: oak release-pdf
      - name: Commit CV.md to kirillsulim/kirillsulim
        env:
          GITHUB_TOKEN: ${{ secrets.KSBENDERBOT_GITHUB_TOKEN }}
        run: oak commit-en-md
      - name: Push jsonresume to gists
        env:
          GIST_TOKEN: ${{ secrets.KIRILLSULIM_GIST_TOKEN }}
        run: oak push-jsonresume-gist
