name: Build

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/checkout@v2
      - name: Install python requirements
        run: pip3 install -r requirements.txt
      - name: Pull docker container
        run: docker pull thomasweise/docker-texlive-full
      - name: Run .pdf
        env:
          GITHUB_TOKEN: fake-token
        run: doge render_pdf --profiles pdf
      - name: Run .md
        env:
          GITHUB_TOKEN: fake-token
        run: doge render_md --langs en --profiles md_for_github
