name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - run: python3 --version
      - uses: actions/checkout@v2
      - name: Install python requirements
        run: pip3 install -r requirements.txt
      - name: Pull docker container
        run: docker pull thomasweise/docker-texlive-full
      - name: Run .pdf
        run: doge render_pdf --profiles pdf
      - name: Run .md
        run: doge render_md --langs en --profiles md_for_github

